### ISSUE TITLE
MWException from line 129 of /srv/mediawiki/w/includes/MagicWord.php: Error: invalid magic word 'getshortdesc'

### ISSUE THREAD

**Issue by Reception123** [StarCitizenTools/mediawiki-extensions-ShortDescription#4]
Getting this when trying to run a maintenance script with a wiki that has ShortDescription enabled: 

`#0 /srv/mediawiki/w/includes/MagicWordFactory.php(230): MagicWord->load('getshortdesc')
#1 /srv/mediawiki/w/includes/parser/Parser.php(4869): MagicWordFactory->get('getshortdesc')
#2 /srv/mediawiki/w/extensions/ShortDescription/includes/Hooks/ParserHooks.php(55): Parser->setFunctionHook('getshortdesc', Array, 1)
#3 /srv/mediawiki/w/includes/HookContainer/HookContainer.php(154): MediaWiki\Extension\ShortDescription\Hooks\ParserHooks->onParserFirstCallInit(Object(Parser))
#4 /srv/mediawiki/w/includes/HookContainer/HookRunner.php(2959): MediaWiki\HookContainer\HookContainer->run('ParserFirstCall...', Array)
#5 /srv/mediawiki/w/includes/parser/Parser.php(532): MediaWiki\HookContainer\HookRunner->onParserFirstCallInit(Object(Parser))
#6 /srv/mediawiki/w/includes/parser/Parser.php(477): Parser->firstCallInit()
#7 /srv/mediawiki/w/includes/parser/ParserFactory.php(142): Parser->__construct(Object(MediaWiki\Config\ServiceOptions), Object(MagicWordFactory), Object(LanguageEn), Object(ParserFactory), 'bitcoin\\:|ftp\\:...', Object(MediaWiki\SpecialPage\SpecialPageFactory), Object(MediaWiki\Linker\LinkRendererFactory), Object(NamespaceInfo), Object(Monolog\Logger), Object(MediaWiki\BadFileLookup), Object(MediaWiki\Languages\LanguageConverterFactory), Object(MediaWiki\HookContainer\HookContainer))
#8 /srv/mediawiki/w/includes/ServiceWiring.php(817): ParserFactory->create()
#9 /srv/mediawiki/w/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}(Object(MediaWiki\MediaWikiServices))
#10 /srv/mediawiki/w/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService('Parser')
#11 /srv/mediawiki/w/includes/MediaWikiServices.php(1000): Wikimedia\Services\ServiceContainer->getService('Parser')
#12 /srv/mediawiki/w/includes/content/WikitextContent.php(373): MediaWiki\MediaWikiServices->getParser()
#13 /srv/mediawiki/w/includes/content/AbstractContent.php(590): WikitextContent->fillParserOutput(Object(Title), 27, Object(ParserOptions), true, Object(ParserOutput))
#14 /srv/mediawiki/w/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput(Object(Title), 27, Object(ParserOptions), true)
#15 /srv/mediawiki/w/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(Object(WikitextContent), true)
#16 /srv/mediawiki/w/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput('main')
#17 /srv/mediawiki/w/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(Object(MediaWiki\Revision\RenderedRevision), Array)
#18 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(Object(MediaWiki\Revision\RenderedRevision), Array)
#19 /srv/mediawiki/w/includes/Revision/RenderedRevision.php(197): call_user_func(Object(Closure), Object(MediaWiki\Revision\RenderedRevision), Array)
#20 /srv/mediawiki/w/includes/Storage/DerivedPageDataUpdater.php(1315): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#21 /srv/mediawiki/w/includes/Storage/DerivedPageDataUpdater.php(1665): MediaWiki\Storage\DerivedPageDataUpdater->getCanonicalParserOutput()
#22 /srv/mediawiki/w/includes/Storage/DerivedPageDataUpdater.php(1452): MediaWiki\Storage\DerivedPageDataUpdater->doParserCacheUpdate()
#23 /srv/mediawiki/w/includes/page/WikiPage.php(2172): MediaWiki\Storage\DerivedPageDataUpdater->doUpdates()
#24 /srv/mediawiki/w/includes/import/ImportableOldRevisionImporter.php(218): WikiPage->doEditUpdates(Object(MediaWiki\Revision\RevisionStoreRecord), Object(User), Array)
#25 /srv/mediawiki/w/includes/import/WikiRevision.php(669): ImportableOldRevisionImporter->import(Object(WikiRevision))
#26 /srv/mediawiki/w/includes/import/WikiImporter.php(371): WikiRevision->importOldRevision()
#27 /srv/mediawiki/w/maintenance/importDump.php(201): WikiImporter->importRevision(Object(WikiRevision))
#28 /srv/mediawiki/w/includes/import/WikiImporter.php(507): BackupReader->handleRevision(Object(WikiRevision), Object(WikiImporter))
#29 /srv/mediawiki/w/includes/import/WikiImporter.php(999): WikiImporter->revisionCallback(Object(WikiRevision))
#30 /srv/mediawiki/w/includes/import/WikiImporter.php(864): WikiImporter->processRevision(Array, Array)
#31 /srv/mediawiki/w/includes/import/WikiImporter.php(802): WikiImporter->handleRevision(Array)
#32 /srv/mediawiki/w/includes/import/WikiImporter.php(612): WikiImporter->handlePage()
#33 /srv/mediawiki/w/maintenance/importDump.php(353): WikiImporter->doImport()
#34 /srv/mediawiki/w/maintenance/importDump.php(286): BackupReader->importFromHandle(Resource id #1090)
#35 /srv/mediawiki/w/maintenance/importDump.php(130): BackupReader->importFromFile('/home/reception...')
#36 /srv/mediawiki/w/maintenance/doMaintenance.php(107): BackupReader->execute()
#37 /srv/mediawiki/w/maintenance/importDump.php(358): require_once('/srv/mediawiki/...')
#38 {main}
`

**Comment by alistair3149** [comment]
I wasn't able to reproduce the issue. Have you tried rebuilding the i18n cache?

**Comment by Reception123** [comment]
> I wasn't able to reproduce the issue. Have you tried rebuilding the i18n cache?

I've tried yes, but the issue still happens when I try to run the importDump.php script.

**Comment by alistair3149** [comment]
I looked through the source code and I have no idea what might have caused it. Would you mind to pull in the latest update to see if it helps to fix the issue?

**Comment by Reception123** [comment]
I was under impression that our code was fully updated but it seems that it missed one of your updates, and it now works. Thank you very much for your help!
